In [1]:
import pandas as pd

%config InlineBackend.figure_format = 'svg'

In [12]:
path = 'cars-epa-pylie.csv'
df = pd.read_csv(path)

In [15]:
df.sample(12)

,make,model,class,drive,transmission,cylinders,engine_displacement,fuel_type,fuel_type_1,city_mpg,highway_mpg,co2,fuel_economy_score,ghg_score
1144,Toyota,Tacoma 4WD,Small Pickup Trucks 4WD,Part-time 4-Wheel Drive,Manual 5-Speed,4,2.7,Regular,Regular Gasoline,19,21,448,4,4
1171,Volkswagen,Golf SportWagen,Small Station Wagons,Front-Wheel Drive,Manual 5-Speed,4,1.8,Regular,Regular Gasoline,25,35,313,6,6
187,Cadillac,ATS AWD,Compact Cars,All-Wheel Drive,Automatic (S8),6,3.6,Regular,Regular Gasoline,19,27,399,5,5
47,Audi,R8 Spyder,Two Seaters,All-Wheel Drive,Auto(AM-S7),10,5.2,Premium,Premium Gasoline,14,22,519,3,3
632,Jaguar,F-Type S Coupe,Two Seaters,Rear-Wheel Drive,Manual 6-Speed,6,3.0,Premium,Premium Gasoline,15,24,485,3,3
467,GMC,Canyon 2WD,Small Pickup Trucks 2WD,Rear-Wheel Drive,Automatic 6-Speed,4,2.5,Regular,Regular Gasoline,20,26,405,5,5
595,Infiniti,Q50S Red Sport AWD,Midsize Cars,All-Wheel Drive,Automatic (S7),6,3.0,Premium,Premium Gasoline,19,26,412,5,5
304,Dodge,Challenger,Midsize Cars,Rear-Wheel Drive,Automatic 8-Speed,8,5.7,Midgrade,Midgrade Gasoline,16,25,466,4,4
645,Jaguar,XJL,Large Cars,Rear-Wheel Drive,Automatic (S8),8,5.0,Premium,Premium Gasoline,15,23,503,3,3
1114,Toyota,Corolla LE Eco,Midsize Cars,Front-Wheel Drive,Automatic (variable gear ratios),4,1.8,Regular,Regular Gasoline,30,40,263,8,8
671,Jeep,Patriot 4WD,Small Sport Utility Vehicle 4WD,4-Wheel Drive,Automatic 6-Speed,4,2.4,Regular,Regular Gasoline,20,25,400,5,5
89,BMW,340i xDrive,Compact Cars,All-Wheel Drive,Manual 6-Speed,6,3.0,Premium,Premium Gasoline,19,29,391,5,5

In [4]:
keep_columns = ['make', 'model', 'class', 'cylinders', 'engine_displacement', 'city_mpg', 'co2']
df = df[keep_columns]
df.sample(5)

,make,model,class,cylinders,engine_displacement,city_mpg,co2
484,GMC,Sierra C15 Cab Chassis 2WD,Special Purpose Vehicle 2WD,8,5.3,15,523
587,Hyundai,Veloster,Compact Cars,4,1.6,27,304
787,Lincoln,MKC FWD,Small Sport Utility Vehicle 2WD,4,2.0,21,387
1119,Toyota,Highlander AWD,Standard Sport Utility Vehicle 4WD,6,3.5,19,405
1203,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,4,2.0,23,348

In [5]:
df.describe()

         cylinders  engine_displacement     city_mpg          co2
count  1208.000000          1208.000000  1208.000000  1208.000000
mean      5.607616             3.115728    20.711921   402.446192
std       1.891421             1.364371     6.105381    99.758916
min       3.000000             0.900000    10.000000    51.000000
25%       4.000000             2.000000    17.000000   335.000000
50%       6.000000             3.000000    20.000000   395.000000
75%       6.000000             3.600000    23.000000   466.000000
max      12.000000             8.400000    58.000000   829.000000

In [6]:
df[df['make']=='Porsche']

,make,model,class,cylinders,engine_displacement,city_mpg,co2
1006,Porsche,911 Carrera,Minicompact Cars,6,3.0,22,355
1007,Porsche,911 Carrera,Minicompact Cars,6,3.0,20,382
1008,Porsche,911 Carrera 4,Minicompact Cars,6,3.0,22,362
1009,Porsche,911 Carrera 4,Minicompact Cars,6,3.0,20,389
1010,Porsche,911 Carrera 4 Cabriolet,Minicompact Cars,6,3.0,21,370
1011,Porsche,911 Carrera 4 Cabriolet,Minicompact Cars,6,3.0,19,395
1012,Porsche,911 Carrera 4 GTS,Minicompact Cars,6,3.0,20,400
1013,Porsche,911 Carrera 4 GTS,Minicompact Cars,6,3.0,18,414
1014,Porsche,911 Carrera 4 GTS Cabriolet,Minicompact Cars,6,3.0,20,402
1015,Porsche,911 Carrera 4 GTS Cabriolet,Minicompact Cars,6,3.0,18,419
1016,Porsche,911 Carrera 4S,Minicompact Cars,6,3.0,21,373
1017,Porsche,911 Carrera 4S,Minicompact Cars,6,3.0,20,392
1018,Porsche,911 Carrera 4S Cabriolet,Minicompact Cars,6,3.0,21,371
1019,Porsche,911 Carrera 4S Cabriolet,Minicompact Cars,6,3.0,19,396
1020,Porsche,911 Carrera Cabriolet,Minicompact Cars,6,3.0,22,365
1021,Porsche,911 Carrera Cabriolet,Minicompact Cars,6,3.0,20,388
1022,Porsche,911 Carrera GTS,Minicompact Cars,6,3.0,20,391
1023,Porsche,911 Carrera GTS,Minicompact Cars,6,3.0,18,418
1024,Porsche,911 Carrera GTS Cabriolet,Minicompact Cars,6,3.0,20,400
1025,Porsche,911 Carrera GTS Cabriolet,Minicompact Cars,6,3.0,18,415
1026,Porsche,911 Carrera S,Minicompact Cars,6,3.0,22,363
1027,Porsche,911 Carrera S,Minicompact Cars,6,3.0,20,389
1028,Porsche,911 Carrera S Cabriolet,Minicompact Cars,6,3.0,22,367
1029,Porsche,911 Carrera S Cabriolet,Minicompact Cars,6,3.0,20,391
1030,Porsche,911 Targa 4,Minicompact Cars,6,3.0,22,367
1031,Porsche,911 Targa 4,Minicompact Cars,6,3.0,19,395
1032,Porsche,911 Targa 4 GTS,Minicompact Cars,6,3.0,20,404
1033,Porsche,911 Targa 4 GTS,Minicompact Cars,6,3.0,18,428
1034,Porsche,911 Targa 4S,Minicompact Cars,6,3.0,21,376
1035,Porsche,911 Targa 4S,Minicompact Cars,6,3.0,19,396
1036,Porsche,911 Turbo,Minicompact Cars,6,3.8,19,428
1037,Porsche,911 Turbo Cabriolet,Minicompact Cars,6,3.8,19,430
1038,Porsche,911 Turbo S,Minicompact Cars,6,3.8,19,428
1039,Porsche,911 Turbo S Cabriolet,Minicompact Cars,6,3.8,19,430
1040,Porsche,Boxster,Two Seaters,4,2.0,22,353
1041,Porsche,Boxster,Two Seaters,4,2.0,21,369
1042,Porsche,Boxster S,Two Seaters,4,2.5,21,372
1043,Porsche,Boxster S,Two Seaters,4,2.5,20,401
1044,Porsche,Cayenne,Standard Sport Utility Vehicle 4WD,6,3.6,18,432
1045,Porsche,Cayenne GTS,Standard Sport Utility Vehicle 4WD,6,3.6,16,476
1046,Porsche,Cayenne Platinum,Standard Sport Utility Vehicle 4WD,6,3.6,17,453
1047,Porsche,Cayenne S,Standard Sport Utility Vehicle 4WD,6,3.6,17,452
1048,Porsche,Cayenne S e-Hybrid,Standard Sport Utility Vehicle 4WD,6,3.0,21,258
1049,Porsche,Cayenne Turbo,Standard Sport Utility Vehicle 4WD,8,4.8,14,536
1050,Porsche,Cayenne Turbo S,Standard Sport Utility Vehicle 4WD,8,4.8,14,536
1051,Porsche,Macan,Small Sport Utility Vehicle 4WD,4,2.0,20,399
1052,Porsche,Macan GTS,Small Sport Utility Vehicle 4WD,6,3.0,17,461
1053,Porsche,Macan S,Small Sport Utility Vehicle 4WD,6,3.0,17,459
1054,Porsche,Macan Turbo,Small Sport Utility Vehicle 4WD,6,3.6,17,467
1055,Porsche,Macan Turbo Kit,Small Sport Utility Vehicle 4WD,6,3.6,17,460

In [7]:
pd.value_counts(df['cylinders']).plot.bar()

In [8]:
df[df['cylinders'] > 8]

,make,model,class,cylinders,engine_displacement,city_mpg,co2
17,Aston Martin,Rapide S,Subcompact Cars,12,6.0,14,533
18,Aston Martin,V12 Vantage S,Two Seaters,12,6.0,12,624
19,Aston Martin,V12 Vantage S,Two Seaters,12,6.0,10,724
20,Aston Martin,Vanquish S Zagato,Minicompact Cars,12,6.0,13,555
46,Audi,R8,Two Seaters,10,5.2,14,519
47,Audi,R8 Spyder,Two Seaters,10,5.2,14,519
60,Bentley,Bentayga,Standard Sport Utility Vehicle 4WD,12,6.0,12,596
62,Bentley,Continental GT,Compact Cars,12,6.0,12,580
64,Bentley,Continental GT Convertible,Subcompact Cars,12,6.0,12,604
66,Bentley,Flying Spur,Midsize Cars,12,6.0,12,604
149,BMW,M760i xDrive,Large Cars,12,6.6,13,571
330,Dodge,Viper,Two Seaters,10,8.4,12,623
337,Ferrari,F12 Berlinetta,Two Seaters,12,6.3,12,672
338,Ferrari,F12 Berlinetta,Two Seaters,12,6.3,12,662
339,Ferrari,F12 tdf,Two Seaters,12,6.3,11,711
340,Ferrari,F12 tdf,Two Seaters,12,6.3,11,697
341,Ferrari,GTC4Lusso,Minicompact Cars,12,6.3,11,674
342,Ferrari,GTC4Lusso,Minicompact Cars,12,6.3,12,661
343,Ferrari,LaFerrari Aperta,Two Seaters,12,6.3,12,683
729,Lamborghini,Aventador Coupe,Two Seaters,12,6.5,11,676
730,Lamborghini,Aventador Coupe LP740-4,Two Seaters,12,6.5,10,746
731,Lamborghini,Aventador Roadster,Two Seaters,12,6.5,10,698
732,Lamborghini,Aventador Roadster LP740-4,Two Seaters,12,6.5,10,746
733,Lamborghini,Huracan,Two Seaters,10,5.2,14,532
734,Lamborghini,Huracan 2WD,Two Seaters,10,5.2,14,532
735,Lamborghini,Huracan Spyder,Two Seaters,10,5.2,14,547
736,Lamborghini,Huracan Spyder 2WD,Two Seaters,10,5.2,14,547
852,Mercedes-Benz,AMG G65,Standard Sport Utility Vehicle 4WD,12,6.0,11,762
867,Mercedes-Benz,AMG S65,Large Cars,12,6.0,13,552
869,Mercedes-Benz,AMG SL65,Two Seaters,12,6.0,13,546
905,Mercedes-Benz,Maybach S600,Large Cars,12,6.0,13,565
913,Mercedes-Benz,S600,Large Cars,12,6.0,13,547
914,Mercedes-Benz,S65 AMG Convertible,Subcompact Cars,12,6.0,14,542
915,Mercedes-Benz,S65 AMG Coupe,Compact Cars,12,6.0,13,553
1062,Rolls-Royce,Dawn,Compact Cars,12,6.6,12,627
1063,Rolls-Royce,Ghost,Large Cars,12,6.6,12,627
1064,Rolls-Royce,Ghost EWB,Large Cars,12,6.6,12,627
1065,Rolls-Royce,Phantom,Large Cars,12,6.7,11,638
1066,Rolls-Royce,Phantom Coupe,Compact Cars,12,6.7,11,638
1067,Rolls-Royce,Phantom Drophead Coupe,Compact Cars,12,6.7,11,637
1068,Rolls-Royce,Phantom EWB,Large Cars,12,6.7,11,637
1069,Rolls-Royce,Wraith,Midsize Cars,12,6.6,12,604

In [9]:
df.groupby(['make']).max()

,model,class,cylinders,engine_displacement,city_mpg,co2
make,,,,,,
Acura,TLX FWD,Two Seaters,6,3.5,29,424
Alfa Romeo,Giulia AWD,Two Seaters,6,2.9,24,451
Aston Martin,Vanquish S Zagato,Two Seaters,12,6.0,14,724
Audi,TTS Coupe,Two Seaters,10,5.2,33,519
BMW,i8,Subcompact Cars,12,6.6,31,571
Bentley,Mulsanne EWB,Subcompact Cars,12,6.8,15,692
Buick,Verano,Subcompact Cars,6,3.6,27,518
Cadillac,XTS LIMO,Standard Sport Utility Vehicle 4WD,8,6.2,22,533
Chevrolet,Volt,"Vans, Passenger Type",8,6.2,49,716
Chrysler,Pacifica Plug-in Hybrid,Minivan - 2WD,8,5.7,32,466
Dodge,Viper,Two Seaters,10,8.4,19,623
Ferrari,LaFerrari Aperta,Two Seaters,12,6.3,16,711
Fiat,500 X AWD,Two Seaters,4,2.4,31,364
Ford,Transit T150 Wagon FFV,"Vans, Passenger Type",8,5.2,43,654
GMC,Yukon K1500 XL 4WD,"Vans, Passenger Type",8,6.2,22,716
Genesis,G90 RWD,Large Cars,8,5.0,18,502
Honda,Ridgeline FWD,Standard Pickup Trucks 4WD,6,3.5,49,424
Hyundai,Veloster,Small Sport Utility Vehicle 4WD,6,3.3,57,475
Infiniti,QX80 4WD,Subcompact Cars,8,5.6,28,593
Jaguar,XJL AWD,Two Seaters,8,5.0,32,503
Jeep,Wrangler Unlimited 4WD,Standard Sport Utility Vehicle 4WD,8,6.4,24,592
Kia,Sportage FWD,Small Station Wagons,8,5.0,52,512
Lamborghini,Huracan Spyder 2WD,Two Seaters,12,6.5,14,746
Land Rover,Range Rover Sport,Standard Sport Utility Vehicle 4WD,8,5.0,22,570
Lexus,RX 450h AWD,Subcompact Cars,8,5.7,43,596
Lincoln,Navigator L 4WD,Standard Sport Utility Vehicle 4WD,6,3.7,41,546
Lotus,Evora,Minicompact Cars,6,3.5,17,468
MINI,John Cooper Works Hardtop,Subcompact Cars,4,2.0,28,367
Maserati,Quattroporte SQ4 V6,Subcompact Cars,8,4.7,17,577
Mazda,MX-5,Two Seaters,4,2.5,32,390
McLaren Automotive,570S Coupe,Two Seaters,8,3.8,16,481
Mercedes-Benz,SLC300,Two Seaters,12,6.0,25,829
Mitsubishi,Outlander Sport 4WD,Small Sport Utility Vehicle 4WD,6,3.0,37,388
Nissan,Versa,Two Seaters,8,5.6,33,588
Porsche,Macan Turbo Kit,Two Seaters,8,4.8,22,536
Ram,Promaster City,Standard Pickup Trucks 4WD,8,5.7,21,580
Rolls-Royce,Wraith,Midsize Cars,12,6.7,12,638
Roush Performance,Stage 3 Mustang,Subcompact Cars,8,5.0,14,559
Subaru,WRX,Small Station Wagons,6,3.6,28,458
Toyota,Yaris iA,Subcompact Cars,8,5.7,58,632
Volkswagen,Touareg,Subcompact Cars,6,3.6,28,462
Volvo,XC90 FWD,Standard Sport Utility Vehicle 4WD,4,2.0,25,399
smart,fortwo coupe,Two Seaters,3,0.9,33,258

In [10]:
df[df['cylinders'] == 12].groupby(['make']).mean()

               cylinders  engine_displacement   city_mpg      co2
make
Aston Martin        12.0                 6.00  12.250000  609.000
BMW                 12.0                 6.60  13.000000  571.000
Bentley             12.0                 6.00  12.000000  596.000
Ferrari             12.0                 6.30  11.571429  680.000
Lamborghini         12.0                 6.50  10.250000  716.500
Mercedes-Benz       12.0                 6.00  12.857143  581.000
Rolls-Royce         12.0                 6.65  11.500000  629.375

In [11]:
df.sort_values(by=['engine_displacement'], ascending=False).head()

,make,model,class,cylinders,engine_displacement,city_mpg,co2
330,Dodge,Viper,Two Seaters,10,8.4,12,623
67,Bentley,Mulsanne,Midsize Cars,8,6.8,11,652
68,Bentley,Mulsanne EWB,Midsize Cars,8,6.8,11,692
1065,Rolls-Royce,Phantom,Large Cars,12,6.7,11,638
1066,Rolls-Royce,Phantom Coupe,Compact Cars,12,6.7,11,638